// VhdlSimulatorTests: part of logisim-evolved.
//
// Derived from logisim-evolution, GPL-3.0-only. See LICENSE.md.
//
// The two sim-file generators produce source an external tool consumes, so what matters is the
// bytes, not the shape. Two things are pinned here:
//
//   * the embedded templates match `resources/logisim/hdl/top_sim.templ` and
//     `resources/logisim/sim/comp.templ` byte for byte, **including the trailing newline** a
//     Swift `"""` literal drops. That is the defect class that already cost `VhdlContent`'s
//     template a byte. Where the upstream tree is reachable the comparison is against the real
//     file; everywhere else the byte count is asserted numerically, so CI still catches it.
//   * the generated blocks reproduce upstream's separator placement, including the asymmetry
//     where the `;` between ports runs across component boundaries while the ones inside
//     `component` and `port map` reset per component.

import Foundation
import Testing

@testable import LogisimKernel
@testable import LogisimVhdl

// MARK: - Fixtures

private func port(_ name: String, _ direction: VhdlPortDirection, _ width: Int)
  -> VhdlPortDescription
{
  VhdlPortDescription(name: name, direction: direction, width: BitWidth.known(width))
}

private let oneEntity = [
  VhdlSimulatorEntity(
    simulationName: "LogisimVhdlSimComp_0",
    ports: [port("clock", .input, 1), port("val", .input, 4), port("max", .output, 1)])
]

private let twoEntities =
  oneEntity + [
    VhdlSimulatorEntity(
      simulationName: "LogisimVhdlSimComp_1", ports: [port("a", .input, 1), port("q", .output, 8)])
  ]

/// `~/Developer/logisim/upstream-java-4.1.0/.../resources/logisim`, when this machine has it.
/// Returns nil elsewhere, so the suite still runs on a checkout without the Java tree.
private func upstreamResource(_ relative: String) -> Data? {
  let base = FileManager.default.homeDirectoryForCurrentUser
    .appendingPathComponent("Developer/logisim/upstream-java-4.1.0/src/main/resources/resources/logisim")
  return try? Data(contentsOf: base.appendingPathComponent(relative))
}

// MARK: - Template byte-exactness

@Test func topSimTemplateMatchesTheUpstreamResourceIncludingTheTrailingNewline() {
  #expect(VhdlSimulatorVhdlTop.template.utf8.count == 869)
  #expect(VhdlSimulatorVhdlTop.template.hasSuffix("\n"))
  if let upstream = upstreamResource("hdl/top_sim.templ") {
    #expect(Data(VhdlSimulatorVhdlTop.template.utf8) == upstream)
  }
}

@Test func compTemplateMatchesTheUpstreamResourceIncludingTheTrailingNewline() {
  #expect(VhdlSimulatorTclComp.template.utf8.count == 1107)
  #expect(VhdlSimulatorTclComp.template.hasSuffix("\n"))
  if let upstream = upstreamResource("sim/comp.templ") {
    #expect(Data(VhdlSimulatorTclComp.template.utf8) == upstream)
  }
}

// MARK: - The three generated blocks

@Test func portsSectionPrefixesEveryPortWithItsEntityName() {
  let expected = """
    Autogenerated by \(VhdlBuildInfo.displayName) --
          LogisimVhdlSimComp_0_clock : in std_logic;
          LogisimVhdlSimComp_0_val : in std_logic_vector(3 downto 0);
          LogisimVhdlSimComp_0_max : out std_logic
          ---------------------------

    """
  // Note there is no blank line before the dashes when at least one port was emitted: the
  // trailing `ports.append(lineSeparator)` is what terminates the *last port's* line, since
  // the per-port writes deliberately do not end in one. With no ports at all that same
  // separator lands straight after the header and does produce a blank line; see
  // `generatingWithNoEntitiesStillProducesTheSeparatorLines`.
  #expect(VhdlSimulatorVhdlTop.portsSection(for: oneEntity) == expected)
}

/// `firstPort` is a field in Java, initialised once *before* the component loop and only ever
/// cleared, so the `;` separator carries across the boundary between two components, unlike
/// `firstComp`/`firstMap`, which are reset inside the loop. A port-list generator that reset it
/// per component would emit a syntactically broken entity here.
@Test func portsSectionSeparatorRunsAcrossComponentBoundaries() {
  let section = VhdlSimulatorVhdlTop.portsSection(for: twoEntities)
  #expect(section.contains("LogisimVhdlSimComp_0_max : out std_logic;\n      LogisimVhdlSimComp_1_a"))
}

@Test func componentsSectionResetsItsSeparatorPerComponent() {
  let expected = """
    Autogenerated by \(VhdlBuildInfo.displayName) --
       component LogisimVhdlSimComp_0
          port (
             clock : in std_logic;
             val : in std_logic_vector(3 downto 0);
             max : out std_logic
          );
       end component ;
      \u{20}
       ---------------------------

    """
  #expect(VhdlSimulatorVhdlTop.componentsSection(for: oneEntity) == expected)
}

@Test func mapSectionWiresEachPortToItsPrefixedTopPort() {
  let expected = """
    Autogenerated by \(VhdlBuildInfo.displayName) --
       LogisimVhdlSimComp_0_map : LogisimVhdlSimComp_0 port map (
          clock => LogisimVhdlSimComp_0_clock,
          val => LogisimVhdlSimComp_0_val,
          max => LogisimVhdlSimComp_0_max
       );
      \u{20}
       ---------------------------

    """
  #expect(VhdlSimulatorVhdlTop.mapSection(for: oneEntity) == expected)
}

@Test func aOneBitPortHasNoVectorSuffixAndAWidePortIsDownToZero() {
  let section = VhdlSimulatorVhdlTop.componentsSection(for: twoEntities)
  #expect(section.contains("a : in std_logic;"))
  #expect(section.contains("q : out std_logic_vector(7 downto 0)"))
}

@Test func generatingWithNoEntitiesStillProducesTheSeparatorLines() {
  // `generateFiles` calls `generate` unconditionally, so an empty component list is reachable.
  let section = VhdlSimulatorVhdlTop.portsSection(for: [])
  #expect(section == "Autogenerated by \(VhdlBuildInfo.displayName) --\n\n      ---------------------------\n")
}

// MARK: - Full-file substitution

@Test func generateSubstitutesAllFourPlaceholdersAndLeavesNoneBehind() {
  let text = VhdlSimulatorVhdlTop.generate(entities: oneEntity, date: "2026-09-05T12:00:00+0000")
  #expect(!text.contains("%date%"))
  #expect(!text.contains("%ports%"))
  #expect(!text.contains("%components%"))
  #expect(!text.contains("%map%"))
  #expect(text.contains("-- Date    :  2026-09-05T12:00:00+0000"))
  // The template's own `    -- ` opens the comment that the generated block's trailing `--`
  // closes; getting that pairing wrong is invisible until a VHDL compiler sees it.
  #expect(text.contains("    -- Autogenerated by \(VhdlBuildInfo.displayName) --\n"))
  #expect(text.hasSuffix("end comp;\n"))
}

@Test func compScriptListsOneVcomLinePerEntity() {
  let text = VhdlSimulatorTclComp.generate(entities: twoEntities, date: "2026-09-05T12:00:00+0000")
  #expect(text.contains("# Autogenerated by logisim\n"))
  #expect(
    text.contains("vcom -reportprogress 300 -work work ../src/LogisimVhdlSimComp_0.vhdl\n"))
  #expect(
    text.contains("vcom -reportprogress 300 -work work ../src/LogisimVhdlSimComp_1.vhdl\n"))
  // The Tcl `$errmsg` in the template is not a regex replacement reference and must survive.
  #expect(text.contains("puts \"Compilation error: $errmsg\""))
  #expect(!text.contains("%comp_files%"))
}

/// Upstream does *not* interpolate `BuildInfo.displayName` in the Tcl generator, only in the
/// VHDL one, and does not append the closing `--`. Both are upstream's inconsistency.
@Test func theTclGeneratorUsesTheLiteralHeaderNotTheBuildDisplayName() {
  let previous = VhdlBuildInfo.displayName
  defer { VhdlBuildInfo.displayName = previous }
  VhdlBuildInfo.displayName = "something-else"
  #expect(VhdlSimulatorTclComp.compileCommands(for: []) == "Autogenerated by logisim\n")
  #expect(
    VhdlSimulatorVhdlTop.portsSection(for: []).hasPrefix("Autogenerated by something-else --\n"))
}

// MARK: - Date formatting

@Test func theDateFormatIsRfc822NotIso8601() {
  // `SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ")`: `Z` is `+0000`, with no colon.
  let text = VhdlSimulatorVhdlTop.formattedNow(Date(timeIntervalSince1970: 0))
  #expect(text.count == 24)
  #expect(text.contains("T"))
  #expect(text.range(of: "[+-][0-9]{4}$", options: .regularExpression) != nil)
}

// MARK: - VhdlSimConstants

@Test func simPathsAgreeWithUpstreamsConcatenation() {
  // Java: `System.getProperty("java.io.tmpdir") + "/logisim/sim/"`, and `java.io.tmpdir` already
  // ends in a separator, so the doubled slash is upstream's, and is preserved (see the note in
  // `VhdlSimConstants`).
  #expect(VhdlSimConstants.simPath.hasSuffix("//logisim/sim/"))
  #expect(VhdlSimConstants.simSrcPath == VhdlSimConstants.simPath + "src/")
  #expect(VhdlSimConstants.simCompPath == VhdlSimConstants.simPath + "comp/")
  #expect(VhdlSimConstants.simTopFilename == "top_sim.vhdl")
  #expect(VhdlSimConstants.vhdlComponentSimName == "LogisimVhdlSimComp_")
}

@Test func theSimNameAttributeIsOneInstanceSharedWithVhdlEntityAttributes() {
  // `AbstractAttributeSet` dispatches on object identity; two attributes with the same name
  // would make every lookup through the other spelling silently return nil.
  #expect(VhdlSimConstants.simNameAttribute === VhdlEntityAttributes.simNameAttribute)
  #expect(VhdlSimConstants.simNameAttribute.isHidden)
}

@Test func theSimulatorStateEnumPrintsJavasConstantNames() {
  #expect(VhdlSimulatorState.allCases.map(\.description) == [
    "DISABLED", "ENABLED", "STARTING", "RUNNING",
  ])
}
