// IoHdlOracleTests: part of logisim-evolved.
//
// The differential gate for the std/io HDL generators: every case here is generated by the
// Swift port and compared byte-for-byte against `tools/hdlbridge/io-4.1.0.oracle`, which was
// produced by driving the real 4.1.0 classes inside the shipped jar
// (`tools/hdlbridge/IoBridge.java`). Case names and the netlist setup mirror the bridge exactly.
//
// GPL-3.0-only; see LICENSE.md.

import Foundation
import LogisimFile
import LogisimHdl
import LogisimKernel
import LogisimStd
import Testing

// MARK: - The attribute wiring the integrator must reproduce

/// The `IoHdlAttributes` the registration in `HdlGeneratorLookup` should install. This is the
/// real wiring, exercised by the gate, not a test double, so if the report's registration
/// snippet and this disagree, the gate catches it.
private func ioAttributes() -> IoHdlAttributes {
  IoHdlAttributes(
    isButtonPressPassive: { attrs in
      guard attrs.containsAttribute(Button.press) else { return false }
      guard case .option(let option)? = attrs.rawValue(Button.press) else { return false }
      return option == Button.pressPassive
    },
    isLedBarSingleBus: { attrs in
      guard attrs.containsAttribute(LedBar.ledBarInputType) else { return false }
      guard case .option(let option)? = attrs.rawValue(LedBar.ledBarInputType) else { return false }
      return option == LedBar.inputOneWire
    },
    ledBarColumns: { attrs in Int(attrs.getValue(LedBar.attrMatrixCols)?.width ?? 0) },
    dotMatrixInputType: { attrs in
      guard attrs.containsAttribute(DotMatrixBase.attrInputType),
        case .option(let option)? = attrs.rawValue(DotMatrixBase.attrInputType)
      else { return .select }
      if option == DotMatrixBase.inputColumn { return .column }
      if option == DotMatrixBase.inputRow { return .row }
      return .select
    },
    dotMatrixRows: { attrs in Int(attrs.getValue(DotMatrix.attrMatrixRows)?.width ?? 0) },
    dotMatrixColumns: { attrs in Int(attrs.getValue(DotMatrix.attrMatrixCols)?.width ?? 0) },
    persistTicks: { attrs in
      guard attrs.containsAttribute(DotMatrixBase.attrPersist) else { return 0 }
      return attrs.getValue(DotMatrixBase.attrPersist) ?? 0
    },
    portDirection: { attrs in
      switch attrs.getValue(PortIo.attrDirection) {
      case .output: return .output
      case .inOutSingleEnable: return .inOutSingleEnable
      case .inOutMultiEnable: return .inOutMultiEnable
      default: return .input
      }
    },
    portSize: { attrs in Int(attrs.getValue(PortIo.attrSize)?.width ?? 1) },
    hasDecimalPoint: { attrs in
      guard attrs.containsAttribute(SevenSegment.attrDecimalPoint) else { return false }
      return attrs.getValue(SevenSegment.attrDecimalPoint) ?? false
    })
}

// MARK: - Case recording

private final class IoCaseRecorder {
  private(set) var produced: [String: [String]] = [:]
  private(set) var order: [String] = []

  func record(_ name: String, _ lines: [String]) {
    let key = "\(name)\t\(HdlSettings.language == .vhdl ? "VHDL" : "Verilog")"
    produced[key] = IoOracle.render(lines)
    order.append(key)
  }

  func record(_ name: String, text: [String]) { record(name, text) }
}

// MARK: - Component construction, mirroring IoBridge

private func place(_ factory: any ComponentFactory, _ attrs: any AttributeSet) throws
  -> any Component
{
  try factory.createComponent(location: Location.create(100, 100, hasToSnap: false), attributes: attrs)
}

private func makeInfo(_ component: any Component) -> OracleNetlistComponent {
  OracleNetlistComponent(component: component)
}

private func inlined(
  _ generator: any HdlGeneratorFactory, _ netlist: OracleNetlist, _ info: OracleNetlistComponent
) -> [String] {
  generator.getInlinedCode(
    netlist: netlist, componentId: 1, componentInfo: info, circuitName: "oracleCircuit"
  ).get()
}

// MARK: - The suite

// A `knownFrameworkDivergences` table used to sit here, holding three cases the port could not
// match byte-for-byte because of defects in framework files the io task did not own. All three
// are fixed, so the table is gone:
//
//   * `ReptarLocalBus/entity VHDL`; `Hdl.getExtendedLibrary()` was one blank line short,
//     because a Java text block appends a newline after its last content line and a Swift
//     multi-line literal does not. Fixed in `Hdl.swift`.
//   * `HexDigit/connected=true/dp={false,true} Verilog`: `WithSelectHdlGenerator` emitted
//     `endcase` at five columns where the jar emits three. A Java text block strips the MINIMUM
//     indentation across its content lines *and* its closing delimiter (10 columns here); Swift
//     strips the delimiter's own indentation only, so transcribing the Java's columns verbatim
//     left two extra. Fixed in `WithSelectHdlGenerator.swift`.
//
// The pin test that guarded them is gone too. It was built to fail exactly when the defects were
// fixed, and that is how both were found. Every case in this suite is now plain byte equality.

@Suite("std/io HDL generators vs. the 4.1.0 jar", .serialized)
struct IoHdlOracleTests {

  @Test("every generated case is byte-identical to upstream, in both VHDL and Verilog")
  func matchesOracle() throws {
    hdlGlobalStateLock.lock()
    defer { hdlGlobalStateLock.unlock() }

    let oracle = try IoOracle.load()
    #expect(oracle.count > 0, "the oracle file parsed to zero cases — the gate is not measuring")

    let recorder = IoCaseRecorder()
    let saved = HdlSettings.language
    // `HdlBuildInfo` is a settable stand-in for Java's build-stamped `BuildInfo` and the port
    // deliberately defaults it to this fork's own branding, which appears in every generated
    // file's header remark. Point it at upstream's values for the duration of the gate so the
    // comparison measures the generators rather than the product name.
    let savedName = HdlBuildInfo.name
    let savedUrl = HdlBuildInfo.url
    HdlBuildInfo.name = "Logisim-evolution"
    HdlBuildInfo.url = "https://github.com/logisim-evolution/"
    defer {
      HdlSettings.language = saved
      HdlBuildInfo.name = savedName
      HdlBuildInfo.url = savedUrl
    }

    for language in [HdlLanguage.vhdl, HdlLanguage.verilog] {
      HdlSettings.language = language
      try emitAllCases(into: recorder)
    }

    #expect(recorder.produced.count > 0, "the Swift side produced zero cases")

    var missing: [String] = []
    var mismatched: [String] = []
    var firstDiff = ""
    for key in recorder.order {
      guard let expected = oracle[key] else {
        missing.append(key)
        continue
      }
      let actual = recorder.produced[key] ?? []
      if actual != expected {
        mismatched.append(key)
        if firstDiff.isEmpty {
          firstDiff = """
            first mismatch: \(key)
            --- upstream (\(expected.count) lines)
            \(expected.joined(separator: "\n"))
            --- port (\(actual.count) lines)
            \(actual.joined(separator: "\n"))
            """
        }
      }
    }

    #expect(
      missing.isEmpty,
      "case names not present in the oracle (a typo makes a case silently untested): \(missing)")
    // Coverage, quoted rather than assumed: this suite drives every oracle case except the
    // board-level LED-array family, which `IoLedArrayOracleTests` owns.
    #expect(
      recorder.order.count == 122,
      "this suite now generates \(recorder.order.count) cases, not 122 — update the count and the report")
    #expect(
      mismatched.isEmpty,
      "\(mismatched.count) of \(recorder.order.count) cases differ from the 4.1.0 jar.\n\(firstDiff)"
    )
  }

  // MARK: cases

  private func emitAllCases(into recorder: IoCaseRecorder) throws {
    try simpleIoCases(recorder)
    try hexDigitCases(recorder)
    try ledBarCases(recorder)
    try dotMatrixCases(recorder)
    try portIoCases(recorder)
    try reptarCases(recorder)
  }

  private func simpleIoCases(_ recorder: IoCaseRecorder) throws {
    let attributes = ioAttributes()
    for pressPassive in [false, true] {
      let factory = Button()
      let attrs = factory.createAttributeSet()
      try attrs.setValue(Button.press, pressPassive ? Button.pressPassive : Button.pressActive)
      let comp = try place(factory, attrs)
      let netlist = OracleNetlist()
      let info = makeInfo(comp)
      info.connectAll(in: netlist)
      info.setLocalBubbleId(
        inputStart: 4, nrOfInput: comp.ends.count, outputStart: 0, nrOfOutput: 0, inOutStart: 0,
        nrOfInOut: 0)
      let generator = AbstractSimpleIoHdlGeneratorFactory(
        isInputComponent: true, attributes: attributes)
      recorder.record(
        "Button/press=\(pressPassive ? "passive" : "active")",
        inlined(generator, netlist, info))
    }

    do {
      let factory = Button()
      let attrs = factory.createAttributeSet()
      let comp = try place(factory, attrs)
      let netlist = OracleNetlist()
      let info = makeInfo(comp)
      info.setLocalBubbleId(
        inputStart: 4, nrOfInput: comp.ends.count, outputStart: 0, nrOfOutput: 0, inOutStart: 0,
        nrOfInOut: 0)
      recorder.record(
        "Button/unconnected",
        inlined(
          AbstractSimpleIoHdlGeneratorFactory(isInputComponent: true, attributes: attributes),
          netlist, info))
    }

    for size in [2, 4, 8] {
      let factory = DipSwitch()
      let attrs = factory.createAttributeSet()
      try attrs.setValue(DipSwitch.size, BitWidth.known(size))
      let comp = try place(factory, attrs)
      let netlist = OracleNetlist()
      let info = makeInfo(comp)
      info.connectAll(in: netlist)
      info.setLocalBubbleId(
        inputStart: 3, nrOfInput: comp.ends.count, outputStart: 0, nrOfOutput: 0, inOutStart: 0,
        nrOfInOut: 0)
      recorder.record(
        "DipSwitch/size=\(size)",
        inlined(
          AbstractSimpleIoHdlGeneratorFactory(isInputComponent: true, attributes: attributes),
          netlist, info))
    }

    for (name, connected, start) in [("Led", true, 7), ("Led/unconnected", false, 7)] {
      let factory = Led()
      let attrs = factory.createAttributeSet()
      let comp = try place(factory, attrs)
      let netlist = OracleNetlist()
      let info = makeInfo(comp)
      if connected { info.connectAll(in: netlist) }
      info.setLocalBubbleId(
        inputStart: 0, nrOfInput: 0, outputStart: start, nrOfOutput: comp.ends.count,
        inOutStart: 0, nrOfInOut: 0)
      recorder.record(
        name,
        inlined(
          AbstractSimpleIoHdlGeneratorFactory(isInputComponent: false, attributes: attributes),
          netlist, info))
    }

    do {
      let factory = RgbLed()
      let attrs = factory.createAttributeSet()
      let comp = try place(factory, attrs)
      let netlist = OracleNetlist()
      let info = makeInfo(comp)
      info.connectAll(in: netlist)
      info.setLocalBubbleId(
        inputStart: 0, nrOfInput: 0, outputStart: 11, nrOfOutput: comp.ends.count, inOutStart: 0,
        nrOfInOut: 0)
      recorder.record(
        "RgbLed",
        inlined(
          AbstractSimpleIoHdlGeneratorFactory(isInputComponent: false, attributes: attributes),
          netlist, info))
    }

    for decimalPoint in [false, true] {
      let factory = SevenSegment()
      let attrs = factory.createAttributeSet()
      try attrs.setValue(SevenSegment.attrDecimalPoint, decimalPoint)
      let comp = try place(factory, attrs)
      let netlist = OracleNetlist()
      let info = makeInfo(comp)
      info.connectAll(in: netlist)
      info.setLocalBubbleId(
        inputStart: 0, nrOfInput: 0, outputStart: 2, nrOfOutput: comp.ends.count, inOutStart: 0,
        nrOfInOut: 0)
      recorder.record(
        "SevenSegment/dp=\(decimalPoint)",
        inlined(
          AbstractSimpleIoHdlGeneratorFactory(isInputComponent: false, attributes: attributes),
          netlist, info))
    }
  }

  private func hexDigitCases(_ recorder: IoCaseRecorder) throws {
    let attributes = ioAttributes()
    for connected in [true, false] {
      for decimalPoint in [false, true] {
        let factory = HexDigit()
        let attrs = factory.createAttributeSet()
        try attrs.setValue(SevenSegment.attrDecimalPoint, decimalPoint)
        try attrs.setValue(StdAttr.label, "hd1")
        let comp = try place(factory, attrs)
        let netlist = OracleNetlist()
        let info = makeInfo(comp)
        if connected { info.connectAll(in: netlist) }
        info.setLocalBubbleId(
          inputStart: 0, nrOfInput: 0, outputStart: 16, nrOfOutput: 8, inOutStart: 0, nrOfInOut: 0)
        recorder.record(
          "HexDigit/connected=\(connected)/dp=\(decimalPoint)",
          inlined(HexDigitHdlGeneratorFactory(attributes: attributes), netlist, info))
      }
    }
  }

  private func ledBarCases(_ recorder: IoCaseRecorder) throws {
    let attributes = ioAttributes()
    for oneWire in [true, false] {
      for cols in [1, 4, 8] {
        let factory = LedBar()
        let attrs = factory.createAttributeSet()
        try attrs.setValue(LedBar.attrMatrixCols, BitWidth.known(cols))
        try attrs.setValue(
          LedBar.ledBarInputType, oneWire ? LedBar.inputOneWire : LedBar.inputSeparated)
        let comp = try place(factory, attrs)
        let netlist = OracleNetlist()
        let info = makeInfo(comp)
        info.connectAll(in: netlist)
        info.setLocalBubbleId(
          inputStart: 0, nrOfInput: 0, outputStart: 5, nrOfOutput: cols, inOutStart: 0,
          nrOfInOut: 0)
        recorder.record(
          "LedBar/oneWire=\(oneWire)/cols=\(cols)",
          inlined(LedBarHdlGeneratorFactory(attributes: attributes), netlist, info))
        recorder.record(
          "LedBar/supported/oneWire=\(oneWire)/cols=\(cols)",
          supportedLines(LedBarHdlGeneratorFactory(attributes: attributes), attrs, "LedBar"))
      }
    }
    do {
      let factory = LedBar()
      let attrs = factory.createAttributeSet()
      try attrs.setValue(DotMatrixBase.attrPersist, 3)
      recorder.record(
        "LedBar/supported/persist=3",
        supportedLines(LedBarHdlGeneratorFactory(attributes: attributes), attrs, "LedBar"))
    }
  }

  private func dotMatrixCases(_ recorder: IoCaseRecorder) throws {
    let attributes = ioAttributes()
    let inputTypes: [(AttributeOption, String)] = [
      (DotMatrixBase.inputColumn, "column"),
      (DotMatrixBase.inputRow, "row"),
      (DotMatrixBase.inputSelect, "select"),
    ]
    let shapes = [(1, 1), (1, 3), (3, 1), (2, 2), (5, 7)]
    for (option, name) in inputTypes {
      for (rows, cols) in shapes {
        let factory = DotMatrix()
        let attrs = factory.createAttributeSet()
        try attrs.setValue(DotMatrix.attrMatrixRows, BitWidth.known(rows))
        try attrs.setValue(DotMatrix.attrMatrixCols, BitWidth.known(cols))
        try attrs.setValue(DotMatrixBase.attrInputType, option)
        let comp = try place(factory, attrs)
        let netlist = OracleNetlist()
        let info = makeInfo(comp)
        info.connectAll(in: netlist)
        info.setLocalBubbleId(
          inputStart: 0, nrOfInput: 0, outputStart: 6, nrOfOutput: rows * cols, inOutStart: 0,
          nrOfInOut: 0)
        recorder.record(
          "DotMatrix/\(name)/rows=\(rows)/cols=\(cols)",
          inlined(DotMatrixHdlGeneratorFactory(attributes: attributes), netlist, info))
      }
    }
    do {
      let factory = DotMatrix()
      let attrs = factory.createAttributeSet()
      try attrs.setValue(DotMatrixBase.attrPersist, 2)
      recorder.record(
        "DotMatrix/supported/persist=2",
        supportedLines(DotMatrixHdlGeneratorFactory(attributes: attributes), attrs, "DotMatrix"))
      try attrs.setValue(DotMatrixBase.attrPersist, 0)
      recorder.record(
        "DotMatrix/supported/persist=0",
        supportedLines(DotMatrixHdlGeneratorFactory(attributes: attributes), attrs, "DotMatrix"))
    }
  }

  private func portIoCases(_ recorder: IoCaseRecorder) throws {
    let attributes = ioAttributes()
    let directions: [(PortIoDirection, String)] = [
      (.input, "input"), (.output, "output"), (.inOutSingleEnable, "inoutse"),
      (.inOutMultiEnable, "inoutme"),
    ]
    for (direction, name) in directions {
      for size in [1, 4, 8] {
        let factory = PortIo()
        let attrs = factory.createAttributeSet()
        try attrs.setValue(PortIo.attrSize, BitWidth.known(size))
        try attrs.setValue(PortIo.attrDirection, direction)
        let comp = try place(factory, attrs)
        let netlist = OracleNetlist()
        let info = makeInfo(comp)
        info.connectAll(in: netlist)
        info.setLocalBubbleId(
          inputStart: 9, nrOfInput: size, outputStart: 13, nrOfOutput: size, inOutStart: 21,
          nrOfInOut: size)
        recorder.record(
          "PortIo/\(name)/size=\(size)",
          inlined(PortHdlGeneratorFactory(attributes: attributes), netlist, info))
      }
    }
  }

  private func reptarCases(_ recorder: IoCaseRecorder) throws {
    let factory = ReptarLocalBus()
    let attrs = factory.createAttributeSet()
    let comp = try place(factory, attrs)
    let netlist = OracleNetlist()
    let info = makeInfo(comp)
    info.connectAll(in: netlist)
    info.setLocalBubbleId(
      inputStart: 0, nrOfInput: 13, outputStart: 20, nrOfOutput: 2, inOutStart: 40, nrOfInOut: 16)
    let generator = ReptarLocalBusHdlGeneratorFactory()
    recorder.record(
      "ReptarLocalBus/supported", supportedLines(generator, attrs, "ReptarLocalBus"))
    guard generator.isHdlSupportedTarget(attrs: attrs) else {
      // `AbstractComponentFactory.getHDLGenerator` answers null in Verilog, and the bridge
      // records that as the entity case's whole body before returning.
      recorder.record("ReptarLocalBus/entity", ["<no generator>"])
      return
    }

    recorder.record(
      "ReptarLocalBus/entity",
      generator.getEntity(netlist: netlist, attrs: attrs, componentName: "LocalBus"))
    recorder.record(
      "ReptarLocalBus/architecture",
      generator.getArchitecture(netlist: netlist, attrs: attrs, componentName: "LocalBus") ?? [])
    recorder.record(
      "ReptarLocalBus/instantiation",
      generator.getComponentInstantiation(
        netlist: netlist, attrs: attrs, componentName: "LocalBus"
      ).get())
    recorder.record(
      "ReptarLocalBus/componentMap",
      try generator.getComponentMap(
        netlist: netlist, componentId: 3, componentInfo: info, name: "LocalBus"
      ).get())
    // `ReptarLocalBus.getHDLName(attrs)`; the only io factory that overrides it. This is the
    // `hdlName` closure the registration must install, exercised here rather than described.
    recorder.record("ReptarLocalBus/hdlName", [ioAttributes().label(attrs)])
  }

  /// The bridge's `supported(...)`: what `AbstractComponentFactory.getHDLGenerator(attrs)` and
  /// `isHDLSupportedComponent(attrs)` answer. Java returns **null** from the former when
  /// `isHdlSupportedTarget` is false, which is the behaviour the registration must reproduce.
  private func supportedLines(
    _ generator: any HdlGeneratorFactory, _ attrs: any AttributeSet, _ javaClassName: String
  ) -> [String] {
    let supported = generator.isHdlSupportedTarget(attrs: attrs)
    return [
      "getHDLGenerator=\(supported ? "\(javaClassName)HdlGeneratorFactory" : "null")",
      "isHDLSupportedComponent=\(supported)",
    ]
  }
}
