// NetlistGateTests.swift: part of logisim-evolved.
//
// The netlist gate: the Swift `Netlist` against the shipped 4.1.0 jar's, over the harvested
// corpus.
//
// ── Why this is the gate that matters for HDL ───────────────────────────────────────────────
//
// `getNetId(net)` is emitted verbatim into generated HDL as `s_LOGISIM_NET_<id>` /
// `s_LOGISIM_BUS_<id>`, so if the net *order* diverges, every signal name in every generated
// file diverges with it, and nothing else in the port would notice, because the netlist is
// internally consistent either way. Upstream's order comes from draining a `HashSet<Wire>`, so
// this suite is the evidence that `JavaHashSetOrder` reproduces JVM hash order rather than the
// evidence being "I read the Java and it looked right".
//
// The oracle is generated by `tools/hdlbridge/NetlistBridge.java`, which drives the real
// `Netlist` inside the jar. Regenerate with `tools/hdlbridge/gen_oracle.py`.
//
// Skips itself when `LOGISIM_CORPUS` is unset or the oracle file is absent, like every other
// corpus-backed suite.
//
// Derived from logisim-evolution, GPL-3.0-only. See LICENSE.md.

import Foundation
import LogisimFile
import LogisimHdlWiring
import LogisimHdl
import LogisimKernel
import LogisimStd
import Testing

/// `.serialized` for the same reason as `NetlistTests`: `StdLibraries.registerAll()` and
/// `HdlGeneratorLookup.shared` are process-wide mutable state, and this suite writes the latter.
@Suite("Netlist — the 4.1.0 jar oracle", .serialized)
struct NetlistGateTests {

  /// Locates `tools/hdlbridge/netlist-4.1.0.oracle` by walking up from this source file.
  static func oracleURL() -> URL? {
    if let override = ProcessInfo.processInfo.environment["LOGISIM_NETLIST_ORACLE"] {
      // Existence checked here, not assumed: this feeds an `.enabled(if:)` trait, and an override
      // pointing at nothing would enable a test whose first read returns immediately.
      let candidate = URL(fileURLWithPath: override)
      return FileManager.default.fileExists(atPath: candidate.path) ? candidate : nil
    }
    var directory = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
    for _ in 0..<8 {
      let candidate =
        directory
        .appendingPathComponent("tools/hdlbridge/netlist-4.1.0.oracle")
      if FileManager.default.fileExists(atPath: candidate.path) { return candidate }
      directory = directory.deletingLastPathComponent()
    }
    return nil
  }

  /// One circuit whose Swift report differs from the jar's.
  struct Divergence: CustomStringConvertible {
    let file: String
    let firstDifferingLine: Int
    let expected: String
    let actual: String

    var description: String {
      "\(file) line \(firstDifferingLine):\n    jar:   \(expected)\n    swift: \(actual)"
    }
  }

  // An explicit skip, not a silent `return`. The corpus is coursework and is not
  // published, so in a clean clone this gate has nothing to compare; a gate that
  // returns early still reports as a PASS, which is the one failure mode
  // `tools/gateaudit.py` exists to catch ("does it SKIP?").
  @Test("every DRC-passing corpus circuit builds the same netlist as the jar",
    .enabled(if: ProcessInfo.processInfo.environment["LOGISIM_CORPUS"] != nil,
      "needs LOGISIM_CORPUS: the corpus is coursework and is not in this repository"))
  func netlistsMatchTheJar() throws {
    // `HdlGeneratorLookup.shared` is process-wide and this suite fills it; Swift Testing runs
    // suites in parallel regardless of `.serialized`. See `HdlGlobalStateLock.swift`.
    try withHdlGeneratorLookup { try compareEveryCircuitToTheJar() }
  }

  private func compareEveryCircuitToTheJar() throws {
    // A corpus IS configured, so the operator asked for this gate to run. Data it then cannot
    // find is a miscalibration, not an absence of coursework: `#require` fails here rather than
    // returning a pass over zero comparisons. The intentional-absence case is the trait above.
    _ = try #require(ProcessInfo.processInfo.environment["LOGISIM_CORPUS"])
    // Derived from the corpus, so it ships beside the corpus rather than here. Regenerate with
    // `tools/hdlbridge/gen_oracle.py`, or point `LOGISIM_NETLIST_ORACLE` at an existing copy.
    let oracleURL = try #require(
      Self.oracleURL(), "LOGISIM_CORPUS is set but the netlist oracle is absent")
    let oracleText = try String(contentsOf: oracleURL, encoding: .utf8)

    StdLibraries.registerAll()

    let entries = OracleEntry.parse(oracleText)
    // Upstream decides "is this component in the netlist?" with
    // `ComponentFactory.getHDLGenerator(attrs) != null`, and the per-component generators are not
    // ported yet (see HdlGeneratorLookup.swift). The jar answers that question in the oracle's
    // SYNTH lines, so the answer is taken from there rather than guessed, which is the whole
    // point of having an oracle to hand.
    HdlGeneratorLookup.shared.upstreamGeneratorFactoryNames =
      entries.reduce(into: Set<String>()) { $0.formUnion($1.synthesizableFactories) }
    HdlGeneratorLookup.shared.upstreamSupportedFactoryNames =
      entries.reduce(into: Set<String>()) { $0.formUnion($1.supportedFactories) }
    // The FPGA bubble half of the same seam. Unlike the two sets above this is not oracle data
    // fed back in; it is the real binding proposed for `LogisimHdlWiring`, and
    // `MapInformationOracleTests` is what checks it against the jar. See
    // `FpgaMapInformationBindings.swift`.
    FpgaMapInformationBindings.install(into: HdlGeneratorLookup.shared)

    var compared = 0
    var divergences: [Divergence] = []

    for entry in entries {
      guard entry.lines.contains("DRC 0") else { continue }
      let expectedLines = entry.reportLines
      let url = URL(fileURLWithPath: entry.path)
      guard FileManager.default.fileExists(atPath: url.path),
        let loaded = try? Loader().openLogisimFile(url)
      else { continue }
      guard let circuitName = entry.lines.first(where: { $0.hasPrefix("CIRCUIT ") })?
        .dropFirst("CIRCUIT ".count),
        let circuit = loaded.circuits.first(where: { $0.name == String(circuitName) })
      else { continue }

      let netlists = NetlistSet()
      let netlist = netlists.netlist(for: circuit)
      var sheetNames: [String] = []
      let status = netlist.designRuleCheckResult(isTopLevel: true, sheetNames: &sheetNames)
      let actual = NetlistReport.render(netlist, drcStatus: status)
      compared += 1

      // Diagnostics hook: `LOGISIM_NETLIST_DUMP=<substring of the file name>` prints both full
      // reports side by side. Investigating a divergence needs the whole report, not the first
      // differing line, and regenerating it by hand each time is the slow way.
      if let wanted = ProcessInfo.processInfo.environment["LOGISIM_NETLIST_DUMP"],
        url.lastPathComponent.contains(wanted)
      {
        print("=== jar: \(url.lastPathComponent)")
        for line in expectedLines { print("J| \(line)") }
        print("=== swift: \(url.lastPathComponent)")
        for line in actual { print("S| \(line)") }
      }

      for index in 0..<max(actual.count, expectedLines.count) {
        let expectedLine =
          index < expectedLines.count
          ? normalizeRandomLabelSuffix(expectedLines[index]) : "<missing>"
        let actualLine =
          index < actual.count ? normalizeRandomLabelSuffix(actual[index]) : "<missing>"
        if expectedLine != actualLine {
          divergences.append(
            Divergence(
              file: url.lastPathComponent, firstDifferingLine: index, expected: expectedLine,
              actual: actualLine))
          break
        }
      }
    }

    #expect(compared > 0, "the oracle named no circuit that could be loaded")
    // Measured 2026-09-05: 147 compared, **1 divergent**; the one entry left in
    // `knownDivergences` below. It was 6 until `processSubcircuit` stopped reading an array
    // nothing populates; see that list's header, which is also the record of four wrong
    // rationales. A floor rather than an equality so that growing the corpus does not fail the
    // suite; it exists because "compared > 0" would still pass if the oracle collapsed to a
    // handful of entries.
    //
    // The 147th is `tools/hdlbridge/bubbletree-fixture.circ`, hand-written and checked in
    // because the harvested corpus reaches **none** of the recursive bubble-tree paths: 0 of its
    // 153 DRC-passing circuits has a subcircuit that itself contains a bubble, so every `BUB SUB`
    // line in that half of the oracle reads `global=-` and the whole of
    // `enumerateGlobalBubbleTree` was transcribed and never compared. Deleting the
    // `+ localBubbleInputStartId` term from the port fails exactly one circuit, and it is that
    // one.
    #expect(compared >= 147, "the gate compared \(compared) circuits, fewer than the recorded 147")

    let unexpected = divergences.filter { Self.knownDivergences[$0.file] == nil }
    #expect(
      unexpected.isEmpty,
      """
      \(unexpected.count) of \(compared) circuits diverge from the jar for a reason not on the \
      known list:
      \(unexpected.prefix(10).map(\.description).joined(separator: "\n"))
      """)

    // The list must not rot. A known divergence that has quietly been fixed elsewhere should
    // make this suite fail so the entry gets deleted, not linger as an excuse.
    let stillDiverging = Set(divergences.map(\.file))
    let healed = Self.knownDivergences.keys.filter { !stillDiverging.contains($0) }
    #expect(
      healed.isEmpty,
      """
      these circuits no longer diverge — delete them from knownDivergences:
      \(healed.sorted().joined(separator: "\n"))
      """)
  }

  /// The corpus circuits that do **not** match the jar, each with the reason, so a new divergence
  /// still fails the suite. They are recorded here rather than silently filtered.
  ///
  /// ── FIVE ENTRIES WERE DELETED ON 2026-09-05, AND FOUR OF THEM HAD THE WRONG CAUSE ─────────
  ///
  /// This list held six files. Five of them, including the two distinct files that share a circuit name, `3.3.0__case-484.circ`,
  /// `3.3.0__case-411.circ`, `3.3.0__case-051.circ`, shared one root cause, and it was *not* the cause
  /// three of them were filed under.
  ///
  /// Those three were recorded as "forward-referenced subcircuit", i.e. the placement resolving
  /// to a portless factory. That had been true and was fixed elsewhere; measured now, the
  /// placement resolves correctly and carries its four ends. `3.3.0__case-411.circ` was recorded as
  /// "custom-appearance subcircuit ports", a port-coordinate mismatch: but fixing the pin lookup
  /// alone healed it, so whatever else may be true of custom appearances, a coordinate mismatch
  /// was not what made *this* gate diverge. Only `3.3.0__case-051.circ`'s entry named the real thing;
  /// "subcircuit pin lookup fails", and it was right about all five.
  ///
  /// The real cause: `Netlist.processSubcircuit` read `CircuitAttributes.pinInstances`, which
  /// nothing in this port ever writes (see `Netlist.subcircuitPins(of:)` for why). Every
  /// subcircuit placement with at least one port therefore failed the DRC on its first end. It
  /// hid here because these five files are *exactly* the DRC-passing corpus circuits that contain
  /// a subcircuit with `ends > 0`; the other 142 are flat, and `bubbletree-fixture.circ`'s three
  /// subcircuits all have `ends=0`. So the port passed DRC on zero hierarchical-with-ports
  /// circuits, and the gate read 141/147 with six "known" reasons instead of one.
  ///
  /// Two lessons worth keeping: a plausible cause written next to a failing file is not a measured
  /// one, and the `healed` check below is what forced this; it failed the moment the real fix
  /// landed, rather than letting five stale excuses sit here.
  /// ── EMPTY SINCE 2026-09-06, AND THE LAST ENTRY LEFT WITHOUT ITS CAUSE BEING FOUND ────────
  ///
  /// one corpus file was recorded as "unexplained: two extra net points"; the jar's nets 5 and 6
  /// each held one point the port's did not (`360,180`, `320,180`), both midpoints of a 20-unit
  /// wire on a south-facing `Tunnel`. It stopped diverging on 2026-09-06 and the `healed` check
  /// below is what surfaced that, exactly as intended.
  ///
  /// **Both the heal and the cause are now measured, and the recorded cause was wrong.** The heal
  /// is real rather than a silent skip: `compared >= 147` still passes, so the circuit is still
  /// compared and now matches the jar line for line.
  ///
  /// The cause is `WireRepair`, which stopped being gated behind an environment variable the same
  /// day. `doSplits` cuts every wire at each connection point strictly inside it, and both
  /// phantom coordinates are exactly such cuts: absent from the file, mid-wire, at a component
  /// port. The entry blamed `Tunnel`'s port geometry, which had nothing to do with it.
  ///
  /// I first ruled out the other candidate correctly, that file declares one circuit and
  /// places zero subcircuits, so the same day's `Netlist.standalone` ownership fix cannot reach
  /// it, then started a bisect that timed out, and was about to record "cause not established".
  /// An agent working the simulation failures had already found it from the other end.
  ///
  /// **One cause, reached from three directions**: this unexplained netlist divergence, the four
  /// remaining M3 simulation failures, and twenty-two migration failures. An uncut wire is a
  /// floating net, because `CircuitPoints.add(Wire)` records only `getEnd0()`/`getEnd1()`; a
  /// segment drawn *through* a port is not connected to it until it is cut.
  static let knownDivergences: [String: String] = [:]
}
