// VhdlSimConstants: part of logisim-evolved.
//
// Derived from logisim-evolution (https://github.com/logisim-evolution/logisim-evolution):
// com/cburch/logisim/vhdl/base/VhdlSimConstants.java. Copyright by the Logisim-evolution
// developers. This translation is a derivative work and is therefore licensed
// GPL-3.0-only. See LICENSE.md.
//
// Reference tree: upstream-java-4.1.0 (D16).
//
// ── Scope ────────────────────────────────────────────────────────────────────────────────
//
// Java's `VhdlSimConstants` is three unrelated things wearing one name: the hidden
// `vhdlSimName` attribute, a bag of path/command constants for the QuestaSim/ModelSim
// co-simulation bridge, and one tree walk over a `CircuitState`. The first two are inert data
// and port directly; the third does not, and says so below.
//
// **NOT-PORTED: `VhdlSimConstants.getVhdlComponents(CircuitState, boolean)`.** It walks
// `s.getCircuit().getNonWires()` and `s.getSubstates()`, comparing each component's factory
// class against `VhdlEntity.class` and `VhdlEntityComponent.class`. `CircuitState`, `Circuit`
// and `Component` all live in `LogisimFile`, and `LogisimVhdl` depends on `LogisimKernel`
// only (see `Package.swift`), so this cannot be written here without a dependency edge this
// module is not allowed to add. It is also *only* reachable from `VhdlSimulatorTop`, which is
// itself D11 (see `VhdlNotPorted.swift`), so nothing in the port is waiting on it. Deliberately
// omitted rather than stubbed: a stub returning `[]` would read as "no VHDL components found",
// which is exactly the silent-wrong-answer shape this project keeps getting bitten by.

import Foundation
import LogisimKernel

/// Stand-in for the generated `com.cburch.logisim.generated.BuildInfo`, used by the
/// autogenerated-by header the sim-file generators emit.
///
/// `LogisimHdl` already declares an equivalent `HdlBuildInfo`; this module cannot import it
/// (dependency graph, above), so the constant is duplicated for the same reason
/// `VhdlContent.vhdlKeywords` duplicates `Vhdl.VHDL_KEYWORDS`. Java's value is
/// `"${projectName} v${appVersion}"` stamped at build time (`build.gradle.kts:736`).
public enum VhdlBuildInfo {
  /// `BuildInfo.displayName`. Settable so the app can brand generated files; the generators
  /// below read it at call time, never cache it.
  public static var displayName = "logisim-evolved"
}

/// `VhdlSimConstants.State`; the co-simulation bridge's lifecycle state.
///
/// Kept even though the bridge itself is D11: it is the value type `VhdlSimulatorTop`'s state
/// machine and the (also D11) console GUI both name, and it costs nothing to have the enum
/// present and correct when the bridge is revisited.
public enum VhdlSimulatorState: String, CaseIterable, Sendable {
  case disabled = "DISABLED"
  case enabled = "ENABLED"
  case starting = "STARTING"
  case running = "RUNNING"

  /// Java prints the enum constant's own name in the `UnsupportedOperationException` messages
  /// (`"Cannot disable VHDL simulator from " + state + " state"`); `Enum.toString()` is the
  /// constant name, i.e. upper case.
  public var description: String { rawValue }
}

/// `com.cburch.logisim.vhdl.base.VhdlSimConstants`.
public enum VhdlSimConstants {

  // MARK: The hidden sim-name attribute

  /// `VhdlSimConstants.SIM_NAME_ATTR`, an instance of the private `VhdlSimNameAttribute`.
  ///
  /// Three things about it are load-bearing and all three are reproduced:
  ///   * its name is `"vhdlSimName"`; that is the string a `.circ` would carry;
  ///   * `parse(String)` is the identity, so any text at all is a legal value;
  ///   * `isHidden()` returns true, so no attribute table shows it.
  ///
  /// It is additionally excluded from saving by `VhdlEntityAttributes.isToSave(_:)`, so despite
  /// having a name it never actually reaches a file.
  public static let simNameAttribute: Attribute<String> = Attribute(
    name: "vhdlSimName",
    isHidden: true,
    codec: AttributeCodec(
      parse: { $0 },
      toStandardString: { $0 },
      encode: { .string($0) },
      decode: { if case .string(let text) = $0 { return text } else { return nil } }))

  // MARK: Paths and commands for the QuestaSim/ModelSim bridge (D11 — see `VhdlNotPorted.swift`)

  /// `VhdlSimConstants.ENCODING` (`StandardCharsets.UTF_8`).
  public static let encoding: String.Encoding = .utf8

  /// `VhdlSimConstants.VHDL_TEMPLATES_PATH`. A *classpath* resource prefix in Java, not a
  /// filesystem path; kept verbatim because it is what identifies the two templates this
  /// module embeds (`top_sim.templ`, `vhdl_component.templ`).
  public static let vhdlTemplatesPath = "/resources/logisim/hdl/"

  /// `VhdlSimConstants.SIM_RESOURCES_PATH`. Also a classpath prefix (`comp.templ`,
  /// `questasim_binder.tcl`, `run.tcl`, `modelsim.ini`).
  public static let simResourcesPath = "/resources/logisim/sim/"

  /// `VhdlSimConstants.SIM_PATH` = `System.getProperty("java.io.tmpdir") + "/logisim/sim/"`.
  ///
  /// Computed, not stored, because `NSTemporaryDirectory()` is per-process and a stored `let`
  /// would freeze whatever it was at first touch. Note the doubled separator: `java.io.tmpdir`
  /// on macOS already ends in `/`, and Java concatenates another one, yielding
  /// `…/T//logisim/sim/`. Reproduced rather than cleaned up; every path below is built from
  /// this by concatenation, POSIX treats `//` as `/`, and normalising it here would silently
  /// change filenames the (future) external simulator is handed.
  public static var simPath: String { NSTemporaryDirectory() + "/logisim/sim/" }

  /// `VhdlSimConstants.SIM_SRC_PATH`.
  public static var simSrcPath: String { simPath + "src/" }

  /// `VhdlSimConstants.SIM_COMP_PATH`.
  public static var simCompPath: String { simPath + "comp/" }

  /// `VhdlSimConstants.SIM_TOP_FILENAME`.
  public static let simTopFilename = "top_sim.vhdl"

  /// `VhdlSimConstants.VHDL_COMPONENT_SIM_NAME`. `VhdlSimulatorTop.generateFiles` labels the
  /// i-th VHDL component `LogisimVhdlSimComp_<i>`.
  public static let vhdlComponentSimName = "LogisimVhdlSimComp_"

  /// `VhdlSimConstants.VHDL_COMPILE_COMMAND`. Upstream's own `// FIXME: hardcoded path` sits on
  /// this line; the relative `../src/` is theirs and is preserved because the generated
  /// `comp.tcl` is executed from `SIM_COMP_PATH`, one level below `SIM_PATH`.
  public static let vhdlCompileCommand = "vcom -reportprogress 300 -work work ../src/"
}
