// VhdlSimulatorTclComp: part of logisim-evolved.
//
// Derived from logisim-evolution (https://github.com/logisim-evolution/logisim-evolution):
// com/cburch/logisim/vhdl/sim/VhdlSimulatorTclComp.java. Copyright by the Logisim-evolution
// developers. This translation is a derivative work and is therefore licensed
// GPL-3.0-only. See LICENSE.md.
//
// Reference tree: upstream-java-4.1.0 (D16).
//
// Same split as `VhdlSimulatorVhdlTop`: the live-component walk needs `Project`/`CircuitState`/
// `Component` from `LogisimFile` and cannot be written in this module, so the caller supplies
// `[VhdlSimulatorEntity]`; the text generation is here and is exact.
//
// **NOT-PORTED: the file write.** Java `PrintWriter`s the result to `SIM_PATH + "comp.tcl"`,
// logs and swallows any `IOException`, and memoises with a `valid` flag. That is the
// QuestaSim/ModelSim bridge (D11, see `VhdlNotPorted.swift`); the generated script is a `vcom`
// invocation for a compiler that has no macOS build.
//
// `template` is `resources/logisim/sim/comp.templ` embedded verbatim: 1107 bytes, LF endings,
// trailing newline (the `+ "\n"`, load-bearing, see `VhdlSimulatorVhdlTop`'s header).

import Foundation

/// `com.cburch.logisim.vhdl.sim.VhdlSimulatorTclComp`, reduced to its text generation.
public enum VhdlSimulatorTclComp {

  /// The full `comp.tcl` script: the template with `%date%` and `%comp_files%` substituted.
  ///
  /// - Parameter date: `LocaleManager.PARSER_SDF.format(new Date())`; see
  ///   `VhdlSimulatorVhdlTop.formattedNow(_:)`.
  public static func generate(entities: [VhdlSimulatorEntity], date: String) -> String {
    var result = template
    result = result.replacingOccurrences(of: "%date%", with: date)
    result = result.replacingOccurrences(of: "%comp_files%", with: compileCommands(for: entities))
    return result
  }

  /// The `%comp_files%` block: one `vcom` line per VHDL component.
  ///
  /// Note the header here is the literal string `"Autogenerated by logisim"`; upstream does
  /// *not* interpolate `BuildInfo.displayName` in this generator the way `VhdlSimulatorVhdlTop`
  /// does, and it does not append the closing `--` either (this is a Tcl script, and the
  /// template's own `# ` already opened the comment). Both differences are upstream's;
  /// reproduced rather than harmonised.
  public static func compileCommands(for entities: [VhdlSimulatorEntity]) -> String {
    var out = "Autogenerated by logisim" + VhdlSimulatorVhdlTop.lineSeparator
    for entity in entities {
      out += VhdlSimConstants.vhdlCompileCommand + entity.simulationName + ".vhdl"
        + VhdlSimulatorVhdlTop.lineSeparator
    }
    return out
  }

  // MARK: - The template (`resources/logisim/sim/comp.templ`, embedded verbatim)

  /// 1107 bytes. The `$errmsg` inside is Tcl, not a regex replacement reference: Java's
  /// `replaceAll` treats `$` specially only in the *replacement* string, and this text is the
  /// target.
  public static let template = """
    # ------------------------------------------------------------------------------
    # -- HEIG-VD
    # -- Haute Ecole d'Ingenerie et de Gestion du Canton de Vaud
    # -- School of Business and Engineering in Canton de Vaud
    # ------------------------------------------------------------------------------
    # -- REDS Institute
    # -- Reconfigurable Embedded Digital Systems
    # ------------------------------------------------------------------------------
    # --
    # -- File          : comp.tcl
    # -- Author        : Logisim auto-generated from comp.templ > reds@heig-vd.ch
    # -- Date          : %date%
    # --
    # -- Context       : Logisim advanced simulator run script
    # --                 Compile HDL files
    # ------------------------------------------------------------------------------
    # -- This file has been auto-generated by Logisim, please do not modify.
    # ------------------------------------------------------------------------------


    # Compile components files
    # %comp_files%

    # Compile top sim
    if {[catch {vcom -reportprogress 300 -work work ../src/top_sim.vhdl} errmsg]} {
      puts "Compilation error: $errmsg"
      exit
    }
    """ + "\n"
}
