// CircuitAppearanceReader.swift: part of logisim-evolved.
//
// Derived from logisim-evolution (https://github.com/logisim-evolution/logisim-evolution):
// the `LogisimFile` half of com/cburch/logisim/circuit/appear/AppearanceSvgReader.java plus the
// `CircuitAppearance.setObjectsForce` call `XmlCircuitReader` makes. Copyright by the
// Logisim-evolution developers. This translation is a derivative work and is therefore licensed
// GPL-3.0-only. See LICENSE.md.
//
// ═════════════════════════════════════════════════════════════════════════════════════════════
// WHAT THIS FILE IS
//
// `CircuitAppearanceReader.handler` (declared in `XmlReaderSupport.swift`) is the install point
// for the `<appear>` reader, and until now nothing installed one. The consequence was not that
// appearances were lost, `Circuit.absorbAppearance` keeps the element verbatim under D8, and
// `XmlWriter.fromCircuit`'s `else if` re-emits it, but that they were re-emitted *as read*.
//
// That is wrong for one specific, measurable reason. 4.1.0 writes `<circ-port>` as
// `dir`/`pin`/`x`/`y`; every file written by 2.x or 3.x carries the older
// `x`/`y`/`width`/`height` box instead. Upstream reads the old form, builds an `AppearancePort`,
// and writes the new one: so opening a legacy file and saving it *converts* the section. The
// verbatim path cannot do that, and 17 corpus files failed the migration gate on exactly this
// and nothing else.
//
// ═════════════════════════════════════════════════════════════════════════════════════════════
// THE THREE OUTCOMES OF `createShape`, AND WHY THEY DIFFER
//
//   MODELLED    circ-anchor, circ-origin, circ-port, and every `draw.shapes` tag
//               (rect, ellipse, line, path, polygon, polyline, text). Parsed into a real shape
//               and regenerated by `SvgCreator`/`toSvgElement` on save. This is the set that
//               gets 4.1.0's spelling.
//
//   DROPPED     a `<circ-port>` naming a pin the circuit does not have, or already bound to
//               another port. Upstream returns null here and the caller reports
//               `fileAppearanceNotFound`; the port is genuinely stale and dropping it is
//               correct, not a loss.
//
//   VERBATIM    `visible-*` (the `DynamicElement` families), and any tag nothing recognises.
//               D8: kept as the original element and re-emitted unchanged.
//
// The `visible-*` case is the one worth naming. `LedShape`, `RegisterShape`, `SocVgaShape` and
// the rest live in `LogisimStd`/`LogisimSoc`, above this module, and each binds to a component
// somewhere in the circuit tree; none of them can be constructed from here. Upstream would
// rebuild them from their models. This port keeps the element instead, which is byte-identical
// for any file 4.1.0 itself wrote and lossless for one it did not: the D8 trade, and the same
// one `<vhdl>` and `<boardmap>` already take. Nine such elements exist across the 577 harvested
// corpus files.
//
// An unrecognised tag is a **deliberate divergence**: upstream drops it. D8 says an element we
// do not understand survives load→save rather than being destroyed, and the differential cost
// is zero because no `.circ` in the corpus carries one.
//
// ═════════════════════════════════════════════════════════════════════════════════════════════
// D13
//
// A malformed `<appear>` throws; it never traps. The throw propagates to `XmlReader
// .loadAppearance` / `XmlCircuitReader.buildDynamicAppearance`, which report
// `fileAppearanceError` and continue with the rest of the file; upstream's own behaviour when
// its `RuntimeException` escapes. Two crashes of exactly this kind were already fixed inside
// `LogisimDraw` (an empty `<polygon>` and an out-of-range `<ellipse>` coordinate), and both are
// reachable straight from a `.circ`, so nothing here may re-introduce a trap by "simplifying" a
// `try` away.

import Foundation
import LogisimDraw
import LogisimKernel

// MARK: - D8 carrier

/// An `<appear>` child this port keeps verbatim rather than modelling; see the file header for
/// the two cases that reach it.
///
/// It holds a **detached copy**: the source document is released when the load finishes, and
/// `XmlWriter` copies again before appending, so neither side can re-parent the other's node.
public final class VerbatimAppearanceShape {
  /// The original element, detached from its document.
  public let element: XMLElement

  /// Fails, rather than storing a live node, if the copy cannot be made.
  init?(copying source: XMLElement) {
    guard let duplicate = source.copy() as? XMLElement else { return nil }
    duplicate.detach()
    self.element = duplicate
  }
}

// MARK: - The handler

/// `com.cburch.logisim.circuit.appear.AppearanceSvgReader`, as `XmlReader`/`XmlCircuitReader`
/// call it.
public final class CircuitAppearanceSvgLoader: CircuitAppearanceLoading {

  public init() {}

  /// `Pin.ATTR_TYPE` and its `Pin.OUTPUT` option, reached by name.
  ///
  /// `Pin.isInputPin` lives in `LogisimStd`, which depends on `LogisimFile`, so this module
  /// cannot call it; the same constraint `CircuitSubcircuitFactory.offsetBounds` works under,
  /// and this uses the identical test it does. `XmlReader`'s pre-4.0 repair rewrites the old
  /// `<a name="output" val="true"/>` form into this one before any component is built, so only
  /// the modern spelling has to be recognised.
  private static let pinTypeAttributeName = "type"
  private static let pinTypeOutput = "output"

  /// `AppearanceSvgReader.getPinInfo(Location, Instance)`.
  ///
  /// The direction is resolved **here**, once, because `AppearancePinBinding` (in `LogisimDraw`)
  /// cannot ask a component anything. See `AppearanceElement`'s header for the consequence.
  public func pinInfo(location: Location, component: any Component) -> AnyObject {
    let type = Self.stringValue(of: component.attributeSet, named: Self.pinTypeAttributeName)
    // `PinAttributes.type` defaults to `Pin.INPUT`, so an absent or unrecognised type is an
    // input; the same fallback `CircuitSubcircuitFactory.offsetBounds` uses.
    let isInput = type != Self.pinTypeOutput
    return AppearancePinBinding(location: location, isInput: isInput, reference: component)
  }

  /// `AppearanceSvgReader.createShape(Element, List<PinInfo>, Circuit)`.
  ///
  /// `circuit` is non-nil only on the dynamic pass. It is unused: the one thing upstream needs
  /// it for is `DynamicElement.Path.fromSvgString(pathStr, circuit)`, and the dynamic families
  /// are kept verbatim here rather than resolved (file header).
  public func createShape(
    _ element: XMLElement, pins: [AnyObject]?, circuit: Circuit?
  ) throws -> AppearanceShape? {
    let tag = element.tagName

    // D8: the dynamic families cannot be built from this module, so the element is kept.
    if tag.hasPrefix("visible-") {
      return VerbatimAppearanceShape(copying: element)
    }

    let bindings = (pins ?? []).compactMap { $0 as? AppearancePinBinding }
    if let shape = try AppearanceSvgReader.createShape(Self.svgElement(from: element), pins: bindings)
    {
      return shape
    }

    // Nil from a `circ-*` tag means the port matched no pin: upstream drops it and so does this.
    // Nil from anything else means an unrecognised tag, which D8 keeps.
    if tag == "circ-port" || tag == "circ-anchor" || tag == "circ-origin" { return nil }
    return VerbatimAppearanceShape(copying: element)
  }

  /// `circuit.getAppearance().setObjectsForce(shapes)`.
  ///
  /// There is no live `CircuitAppearance` to hand the list to at this milestone, so it goes into
  /// `CircuitAppearanceStore`: see `CircuitAppearanceWriter.swift`, which is the only reader of
  /// it, and which explains why a side table rather than a field on `Circuit`.
  ///
  /// **`setObjectsForce` is not a setter.** It re-layers the list first, and that reordering is
  /// observable in the saved file, see `layered(_:)`.
  public func setAppearance(_ shapes: [AppearanceShape], for circuit: Circuit) {
    CircuitAppearanceStore.shared.set(Self.layered(shapes), for: circuit)
  }

  /// `CircuitAppearance.setObjectsForce(List, boolean)`'s re-layering pass.
  ///
  /// Upstream's own comment says why it exists: "we force the anchor to be in the last position
  /// (top layer), so it is easier to move, and we force the ports to be next to last (near top
  /// layer), so it matches the simulation rendering."
  ///
  /// The result is a **stable partition** into drawn shapes, then ports, then the anchor, each
  /// group keeping its document order. It is not cosmetic: `getCustomObjectsFromBottom()` returns
  /// this list verbatim and `XmlWriter` emits it in that order, so a file whose `<appear>` opened
  /// with `<circ-anchor>`, which every 2.x/3.x file does, comes back out with the anchor after
  /// the drawn shapes. Fifteen corpus files differ on nothing else.
  ///
  /// `XmlWriter.sort` then moves the `<circ-port>` children to the very end (it special-cases
  /// `appear`), so the *emitted* order is drawn shapes, anchor, ports, which is why the ports'
  /// position here is invisible in the output while the anchor's is not.
  ///
  /// Transliterated rather than rewritten as a partition, because the index arithmetic is
  /// upstream's and a "cleaner" version would have to prove it agrees. Java clones each shape on
  /// the way in; this does not, because the list was built by the reader moments ago and has no
  /// other owner.
  static func layered(_ shapes: [AppearanceShape]) -> [AppearanceShape] {
    guard !shapes.isEmpty else { return shapes }
    var out = shapes
    let end = shapes.count - 1
    var reserved = 0
    var index = end
    while index >= 0 {
      let object = out[index]
      if object is AppearanceAnchor {
        if index != end {
          out.remove(at: index)
          out.append(object)
        }
        reserved += 1
      } else if object is AppearancePort {
        if index != end - reserved {
          out.remove(at: index)
          out.insert(object, at: end - reserved)
        }
        reserved += 1
      }
      index -= 1
    }
    return out
  }

  // MARK: - Bridging

  /// `XMLElement` → `LogisimDraw.SvgElement`.
  ///
  /// `LogisimDraw` deliberately owns a minimal stand-in for `org.w3c.dom.Element` rather than
  /// depending on an XML library (see `SvgElement.swift`), so the two DOMs meet here. Only what
  /// `SvgReader` reads crosses: the tag, the attributes, and the text content. Child *elements*
  /// do not; no shape upstream writes has any, and an element that did would have failed to
  /// match a known tag and been kept verbatim before reaching this point.
  static func svgElement(from element: XMLElement) -> SvgElement {
    let svg = SvgElement(element.tagName)
    for attribute in element.attributes ?? [] {
      guard let name = attribute.name else { continue }
      svg.setAttribute(name, attribute.stringValue ?? "")
    }
    let text = element.textContent
    if !text.isEmpty { svg.appendTextNode(text) }
    return svg
  }

  /// The same `AttributeSet` → standard-string read `CircuitSubcircuitFactory` uses.
  private static func stringValue(of set: any AttributeSet, named name: String) -> String? {
    guard let attribute = set.attribute(named: name),
      let raw = set.rawValue(attribute)
    else { return nil }
    return attribute.standardString(for: raw)
  }
}

// MARK: - Installation

/// Installs both halves of the `<appear>` seam.
///
/// **Both, together, or neither.** The reader populates `CircuitAppearanceStore` and the writer
/// is the only thing that reads it; installing the reader alone would parse every appearance and
/// then throw the result away, while installing the writer alone would find an empty store and
/// claim no circuit has a custom appearance. Either half on its own is a no-op at best, which is
/// why there is one entry point and not two.
///
/// Idempotent, and it must run before the first file is loaded; the same contract
/// `StdLibraries.registerAll()` has, which is where it is called from.
public enum CircuitAppearanceSeam {
  public static func install() {
    CircuitAppearanceReader.handler = CircuitAppearanceSvgLoader()
    CircuitAppearanceWriter.handler = CircuitAppearanceSvgSaver()
  }

  /// Removes both handlers, restoring the pure-D8 verbatim path. Exists for tests that need to
  /// compare the two paths on the same input.
  public static func uninstall() {
    CircuitAppearanceReader.handler = nil
    CircuitAppearanceWriter.handler = nil
  }

  // MARK: - Reading a loaded appearance
  //
  // The codec is not the only consumer. A subcircuit's ports come from its custom appearance;
  // `CircuitAttributes.computePorts` reads `getPortOffsets`, and `CircuitAttributes`'s own
  // comments record `getFacing`/`getOffsetBounds` as blocked on this model existing. The three
  // accessors below are that model's read surface, and they are the *whole* of it: anything else
  // this seam holds is an implementation detail of the round trip.

  /// `circuit.getAppearance().getCustomObjectsFromBottom()`.
  ///
  /// Empty for a circuit with no custom appearance. The order is `setObjectsForce`'s: drawn
  /// shapes, then ports, then the anchor.
  public static func shapes(for circuit: Circuit) -> [AppearanceShape] {
    CircuitAppearanceStore.shared.shapes(for: circuit) ?? []
  }

  /// `circuit.getAppearance().getFacing()`: the anchor's direction, or east when the appearance
  /// has no anchor (upstream's `findAnchor() == null` default).
  public static func facing(of circuit: Circuit) -> Direction {
    for shape in shapes(for: circuit) {
      if let anchor = shape as? AppearanceAnchor { return anchor.facingDirection }
    }
    return .east
  }

  /// `circuit.getAppearance().getPortOffsets(Direction)`.
  ///
  /// Each port's location, made relative to the anchor and rotated from the appearance's own
  /// facing to the requested one, paired with the `Pin` component it binds to. Sorted by
  /// location, which is what upstream's `TreeMap` produces and what `computePorts` iterates.
  ///
  /// Two details are upstream's and are easy to get wrong: the anchor is read from the *whole*
  /// list before any port is translated (a port earlier in the list than the anchor still gets
  /// the offset), and the rotation is skipped entirely, not applied as identity, when the
  /// requested facing already equals the appearance's.
  ///
  /// The pin comes back as `AnyObject?` rather than `Component` because `AppearancePort` holds it
  /// weakly and by identity; see `AppearanceElement`'s header for why the shape cannot name a
  /// component type. Cast it back with `as? any Component`.
  public static func portOffsets(
    of circuit: Circuit, facing: Direction
  ) -> [(offset: Location, pin: AnyObject?)] {
    var anchor: Location?
    var defaultFacing = Direction.east
    var ports: [AppearancePort] = []
    for shape in shapes(for: circuit) {
      if let port = shape as? AppearancePort {
        ports.append(port)
      } else if let element = shape as? AppearanceAnchor {
        anchor = element.location
        defaultFacing = element.facingDirection
      }
    }

    var result: [(offset: Location, pin: AnyObject?)] = []
    for port in ports {
      var loc = port.location
      if let anchor {
        loc = loc.translate(-anchor.x, -anchor.y)
      }
      if facing != defaultFacing {
        loc = loc.rotate(from: defaultFacing, to: facing, xc: 0, yc: 0)
      }
      result.append((loc, port.pinReference))
    }
    // `TreeMap` also *deduplicates* on the key. Two ports resolving to the same offset is only
    // reachable from a hand-edited file; the later one wins there, so it wins here too.
    var seen: [Location: Int] = [:]
    var deduplicated: [(offset: Location, pin: AnyObject?)] = []
    for entry in result {
      if let index = seen[entry.offset] {
        deduplicated[index] = entry
      } else {
        seen[entry.offset] = deduplicated.count
        deduplicated.append(entry)
      }
    }
    return deduplicated.sorted { $0.offset < $1.offset }
  }
}
