// SimPortGeometryTests.swift: part of logisim-evolved.
//
// Derived from logisim-evolution, GPL-3.0-only. See LICENSE.md.
// Reference tree: upstream-java-4.1.0 (D16).
//
// ── Why this gate exists, and what it would have caught ─────────────────────────────────────
//
// `tools/difftest/BoundsOracle.java` compares `getOffsetBounds` against upstream over 6,013 rows,
// and it earned its keep: it took non-hierarchical simulation mismatches from 105 to 9. **It does
// not look at ports at all**, and nothing else in this project ever has.
//
// That gap hid a real defect for the entire life of the M3 gate. `Rom.getOffsetBounds`
// (`Rom.java:166`) *overrides* the shared `RamAppearance.getBounds`, using `SymbolWidth + 40` in
// both branches where the shared one uses `SymbolWidth + xoffset`; upstream's `configurePorts`
// then takes the data-output x from **`instance.getBounds().getWidth()`**, i.e. from that
// override. The port transcribed `Rom.offsetBounds` correctly but routed `Rom.ports` through
// `RamAppearance.ports`, which read `RamAppearance`'s own bounds; 250 instead of 240.
//
// So every evolution-appearance ROM's output port sat **10 units** from the wire that was supposed
// to reach it. Nothing errored. The component loaded, resolved, and propagated; it simply drove a
// net nobody read, and everything downstream settled to `U`. Bounds were correct the whole time,
// which is exactly why a bounds oracle could not see it. Measured cost: **13 of the 1,392 corpus
// oracles**, ~54% of the port's real remaining defects at the time it was found.
//
// A geometry defect is close to invisible from the simulation gate; it presents as "some value is
// U", which is also what an unported component, a missing library and a propagation-ordering bug
// all look like. Comparing the geometry directly turns a day of bisection into one line of diff.
//
// ── The oracle ──────────────────────────────────────────────────────────────────────────────
//
// `$LOGISIM_CORPUS/golden_ports.txt`, one line per component, tab-separated:
//
//     <file-basename> \t <circuit> \t <factory> \t <x>,<y> \t <bx>,<by>,<bw>,<bh> \t <ends>
//
// with `<ends>` space-separated `x,y,IO,width` **in `getEnds()` order**. The order is part of the
// contract, not incidental: `Ram.propagate` and friends index ports by number on every simulation
// step, so two ends swapped is a wrong-port read even when every coordinate is present.
//
// Generated by driving the real 4.1.0 classes, per the technique this project keeps rediscovering
// is the only reliable one: see `docs/experiments/m3-simulation-gate.md` §7 and §10 for the
// generator and the invocation. 46,503 rows over the 594-file corpus; the 53 files that produce a
// `FAIL` line are exactly the 53 upstream itself cannot load, which is a useful check that the
// generator ran rather than silently producing nothing.
//
// ── Scoreboard, not 46,503 assertions ───────────────────────────────────────────────────────
//
// Same reasoning as `TruthTableGoldenTests`: a suite that is red for known-and-recorded reasons
// stops being read. The ratchet is asserted and the breakdown is printed, grouped **by factory**,
// because that is the axis a fix lands on.

import Foundation
import LogisimFile
import LogisimKernel
import Testing

@testable import LogisimStd

// MARK: - Oracle parsing

private struct PortRow: Equatable {
  let circuit: String
  let factory: String
  let location: String
  let bounds: String
  let ends: String
}

/// Mask `XmlReader.generateValidVHDLLabel`'s random 8-hex-digit suffix out of a circuit name
/// **or a factory name**; a subcircuit placement's factory *is* a circuit, so it carries the
/// same random suffix and misses the key in exactly the same way.
///
/// This bit me while building this gate and is worth stating plainly, because it is the third
/// place the same upstream behaviour has silently corrupted a measurement. When a circuit's name
/// is not a legal VHDL identifier, `XmlReader` repairs it and, *if it changed anything*, appends
/// `UUID.randomUUID().toString().substring(0, 8)` (`XmlReader.java:717, :758`). So the oracle run
/// and the port run each invent a **different** name for the same circuit.
///
/// Keyed on the raw name, 2,741 oracle rows and 3,132 port rows failed to pair and looked exactly
/// like "the port invented components and lost others"; a spectacular-looking defect that is
/// entirely an artifact. Every one was inside a circuit called something like
/// `ALU_Decoder_baec266a`. `TruthTableGoldenTests` already buckets this for column *headers*;
/// nothing had noticed it also makes circuit *names* unjoinable.
private let vhdlLabelSuffix = try! NSRegularExpression(pattern: "_[0-9a-f]{8}$")

private func maskCircuitName(_ name: String) -> String {
  vhdlLabelSuffix.stringByReplacingMatches(
    in: name, range: NSRange(name.startIndex..., in: name), withTemplate: "_UUID")
}

private func corpusDirectory() -> URL? {
  guard let path = ProcessInfo.processInfo.environment["LOGISIM_CORPUS"] else { return nil }
  var isDirectory: ObjCBool = false
  guard FileManager.default.fileExists(atPath: path, isDirectory: &isDirectory),
    isDirectory.boolValue
  else { return nil }
  return URL(fileURLWithPath: path)
}

/// `file basename -> [PortRow]`, plus the set of files the generator itself could not load.
private func loadOracle(_ corpus: URL) -> (rows: [String: [PortRow]], failed: Set<String>) {
  let url = corpus.appendingPathComponent("golden_ports.txt")
  guard let text = try? String(contentsOf: url, encoding: .utf8) else { return ([:], []) }
  var rows: [String: [PortRow]] = [:]
  var failed: Set<String> = []
  for line in text.split(separator: "\n", omittingEmptySubsequences: true) {
    let f = line.split(separator: "\t", omittingEmptySubsequences: false)
    if f.first == "FAIL" {
      if f.count > 1 { failed.insert(String(f[1])) }
      continue
    }
    guard f.count >= 6 else { continue }
    rows[String(f[0]), default: []].append(
      PortRow(
        circuit: maskCircuitName(String(f[1])), factory: maskCircuitName(String(f[2])),
        location: String(f[3]),
        bounds: String(f[4]), ends: String(f[5])))
  }
  return (rows, failed)
}

// MARK: - The port's own answer, in the oracle's format

private func endsString(_ component: any Component) -> String {
  component.ends.map { end in
    let io = (end.isInput ? "I" : "") + (end.isOutput ? "O" : "")
    return "\(end.location.x),\(end.location.y),\(io),\(end.width.width)"
  }.joined(separator: " ")
}

private func portRows(of file: LogisimFile) -> [PortRow] {
  var rows: [PortRow] = []
  for circuit in file.circuits {
    for component in circuit.nonWires {
      let b = component.bounds
      rows.append(
        PortRow(
          circuit: maskCircuitName(circuit.name),
          factory: maskCircuitName(component.factory.name),
          location: "\(component.location.x),\(component.location.y)",
          bounds: "\(b.x),\(b.y),\(b.width),\(b.height)",
          ends: endsString(component)))
    }
  }
  return rows
}

/// Order-independent multiset key. Two components of the same factory at the same location are
/// legal (and occur in the corpus), so rows are matched as a *bag* keyed on identity-ish fields
/// rather than by index; `getNonWires()` is a `HashSet` upstream and its order is not a contract.
private func bag(_ rows: [PortRow]) -> [String: Int] {
  var out: [String: Int] = [:]
  for r in rows {
    out["\(r.circuit)\u{1}\(r.factory)\u{1}\(r.location)\u{1}\(r.bounds)\u{1}\(r.ends)",
      default: 0] += 1
  }
  return out
}

// MARK: - The gate

@Suite("M3 — component port geometry against the 4.1.0 Java oracle")
struct SimPortGeometryTests {

  /// **The ratchet.** Components whose full geometry row matches upstream exactly.
  ///
  /// First measured 2026-09-05, against `golden_ports.txt` as generated that day:
  /// **44,076 of 46,450 components byte-identical**, 2,374 with differing geometry, and, the
  /// number worth noticing, **0 components present in the oracle and absent from the port.**
  /// Every placement upstream produces, the port produces. 391 exist only in the port, all of them
  /// factory names 4.1.0 does not have (`BitLabeledTunnel` ×311 and friends: fork-specific types
  /// the corpus declares under `#Wiring`, which upstream drops on load and D8 preserves here).
  ///
  /// Of the 2,374 that differ, **96 are `ROM` and are the `Rom.ports` bug this file's header
  /// describes**; every one off by exactly 10 in the data-output x. The rest are subcircuit
  /// placements differing in `bounds` **only, with every end identical**, which is the
  /// `CircuitAppearance` gap (M6) and does not affect simulation.
  ///
  /// Raise it whenever it rises; never lower it. See the file header for why this is a scoreboard.
  static let floor = 44076

  @Test("component ends match upstream, grouped by factory")
  func portGeometry() throws {
    guard let corpus = corpusDirectory() else {
      print("LOGISIM_CORPUS unset — port-geometry gate skipped")
      return
    }
    let (oracle, generatorFailed) = loadOracle(corpus)
    guard !oracle.isEmpty else {
      print("""
        no port oracle at \(corpus.path)/golden_ports.txt — gate skipped.
        Regenerate with PortsBridge (docs/experiments/m3-simulation-gate.md §10).
        """)
      return
    }
    StdLibraries.registerAll()

    var matched = 0
    var mismatchedByFactory: [String: Int] = [:]
    var missingByFactory: [String: Int] = [:]
    var extraByFactory: [String: Int] = [:]
    var examples: [String: String] = [:]
    /// For rows that did not pair on `(circuit, factory, location)` at all; the interesting
    /// question there is *why* the key missed, so one full row from each side is kept.
    var unpairedExamples: [String: String] = [:]
    var filesCompared = 0
    var filesUnloadable = 0

    for (base, expectedRows) in oracle.sorted(by: { $0.key < $1.key }) {
      if generatorFailed.contains(base) { continue }
      let candidates = ["", "harvested"].map { sub -> URL in
        sub.isEmpty
          ? corpus.appendingPathComponent(base)
          : corpus.appendingPathComponent(sub).appendingPathComponent(base)
      }
      guard let path = candidates.first(where: { FileManager.default.fileExists(atPath: $0.path) })
      else { continue }
      guard let file = try? Loader().openLogisimFile(path) else {
        filesUnloadable += 1
        continue
      }
      filesCompared += 1

      var want = bag(expectedRows)
      let actualRows = portRows(of: file)
      var got = bag(actualRows)

      // Exact rows cancel; what is left on each side is the disagreement.
      for (key, count) in want {
        let common = min(count, got[key] ?? 0)
        if common > 0 {
          matched += common
          want[key] = count - common
          got[key] = (got[key] ?? 0) - common
        }
      }
      // Pair leftovers by (circuit, factory, location): same component, different geometry.
      func index(_ b: [String: Int]) -> [String: [String]] {
        var out: [String: [String]] = [:]
        for (key, n) in b where n > 0 {
          let parts = key.split(separator: "\u{1}", omittingEmptySubsequences: false)
          guard parts.count >= 5 else { continue }
          let id = parts[0...2].joined(separator: "\u{1}")
          for _ in 0..<n { out[id, default: []].append(parts[3...4].joined(separator: "  ")) }
        }
        return out
      }
      let wantIdx = index(want)
      let gotIdx = index(got)
      for (id, wants) in wantIdx {
        let factory = String(id.split(separator: "\u{1}")[1])
        let gots = gotIdx[id] ?? []
        let paired = min(wants.count, gots.count)
        if paired > 0 {
          mismatchedByFactory[factory, default: 0] += paired
          if examples[factory] == nil {
            examples[factory] = """
              \(base)::\(id.split(separator: "\u{1}")[0])  at \(id.split(separator: "\u{1}")[2])
                       java  \(wants[0])
                       swift \(gots[0])
              """
          }
        }
        if wants.count > paired {
          missingByFactory[factory, default: 0] += wants.count - paired
          if unpairedExamples[factory] == nil {
            let circuit = String(id.split(separator: "\u{1}")[0])
            let loc = String(id.split(separator: "\u{1}")[2])
            // Show a same-(circuit, factory) row from the port side, if any, so the reason the
            // key missed, a different location, or none at all, is visible.
            let sameKind = gotIdx.keys.first {
              $0.hasPrefix("\(circuit)\u{1}\(factory)\u{1}") && $0 != id
            }
            let other = sameKind.map { "\n                       port has \($0.split(separator: "\u{1}")[2])  \((gotIdx[$0] ?? ["?"])[0])" } ?? "\n                       port has no unpaired \(factory) in this circuit"
            unpairedExamples[factory] =
              "\(base)::\(circuit)  java at \(loc)  \(wants[0])\(other)"
          }
        }
      }
      for (id, gots) in gotIdx {
        let factory = String(id.split(separator: "\u{1}")[1])
        let wants = wantIdx[id] ?? []
        if gots.count > wants.count {
          extraByFactory[factory, default: 0] += gots.count - wants.count
        }
      }
    }

    let mismatched = mismatchedByFactory.values.reduce(0, +)
    let missing = missingByFactory.values.reduce(0, +)
    let extra = extraByFactory.values.reduce(0, +)
    print("""

      ── M3 port-geometry gate ───────────────────────────────────────────
        oracle files            \(oracle.count)  (\(generatorFailed.count) the generator could not load)
        files compared          \(filesCompared)  (\(filesUnloadable) the port could not load)
        components matched      \(matched)
        geometry differs        \(mismatched)
        in oracle, not in port  \(missing)
        in port, not in oracle  \(extra)
      """)
    for (factory, count) in mismatchedByFactory.sorted(by: { $0.value > $1.value }).prefix(12) {
      print("    differs  ×\(count)  \(factory)")
      if let e = examples[factory] { print("             \(e)") }
    }
    for (factory, count) in missingByFactory.sorted(by: { $0.value > $1.value }).prefix(6) {
      print("    missing  ×\(count)  \(factory)")
      if let e = unpairedExamples[factory] { print("             \(e)") }
    }
    for (factory, count) in extraByFactory.sorted(by: { $0.value > $1.value }).prefix(6) {
      print("    extra    ×\(count)  \(factory)")
    }
    print("")

    #expect(
      matched >= SimPortGeometryTests.floor,
      "port-geometry match count fell below the recorded floor of \(SimPortGeometryTests.floor)")
  }
}
